export const ERROR_NICK_EXISTS = 1;
export const ERROR_EMAIL_EXISTS = 2;
export const ERROR_EMAIL_NOT_EXIST = 3;
export const ERROR_WRONG_PASSWORD = 4;
export const ERROR_USER_NOT_AUTHENTICATED = 5;
export const ERROR_CLIENT_NAME_EXISTS = 6;
export const ERROR_CLIENT_REDIRECT_URL_EXISTS = 7;
export const ERROR_USER_NOT_AUTHORIZED = 8;